sonar.projectKey=gosendeet
sonar.projectName=GoSendeet
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src,cypress
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,cypress/**/*.cy.ts,cypress/**/*.cy.tsx
sonar.exclusions=dist/**,dev-dist/**,node_modules/**,public/**,audit/**,coverage/**,src/**/*.test.ts,src/**/*.test.tsx,cypress/**
